"""
Catalog Expander Script for Joyory SmartMatch.
Safely adds realistic, high-quality products across all categories and price tiers.
Preserves all existing database records (uses get_or_create by name).
"""
import os
import sys
import django
from decimal import Decimal

# Setup Django environment
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(BASE_DIR)
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'smartmatch.settings')
django.setup()

from products.models import Product

EXPANDED_PRODUCTS = [
    # =========================================================================
    # 1. SKINCARE (Budget to Luxury, various skin types & concerns)
    # =========================================================================
    {
        'name': 'Gentle Hydrating Amino Acid Cleanser',
        'brand': 'Joyory Pure',
        'category': 'skincare',
        'description': 'A gentle, low-pH foaming cleanser infused with amino acids and panthenol that removes impurities without stripping moisture.',
        'price': Decimal('299.00'),
        'discount_percent': 10,
        'rating': Decimal('4.65'),
        'review_count': 142,
        'image_url': 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'sensitive',
        'concern_tags': 'hydration,dryness,redness,barrier-repair',
        'key_ingredients': 'Amino Acids, Panthenol, Chamomile Extract, Allantoin',
        'full_ingredients': 'Aqua, Sodium Cocoyl Glycinate, Glycerin, Cocamidopropyl Betaine, Panthenol, Chamomilla Recutita Flower Extract, Allantoin, Citric Acid, Phenoxyethanol, Ethylhexylglycerin',
        'usage_instructions': 'Lather a small amount with water in hands. Massage onto damp face in circular motions for 60 seconds, then rinse with lukewarm water.',
        'caution_info': 'For external use only. Avoid direct eye contact.',
        'availability': 'in_stock',
        'is_bestseller': True,
        'is_new_arrival': False,
    },
    {
        'name': '2% BHA Salicylic Clarifying Serum',
        'brand': 'DermaLuxe Botanics',
        'category': 'skincare',
        'description': 'Targeted pore-clearing serum with 2% Salicylic Acid and Zinc PCA to banish blackheads, reduce breakouts, and balance excess sebum.',
        'price': Decimal('549.00'),
        'discount_percent': 15,
        'rating': Decimal('4.72'),
        'review_count': 230,
        'image_url': 'https://images.unsplash.com/photo-1608248597359-00f745771ffb?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'oily',
        'concern_tags': 'acne,pores,oil-control,blackheads',
        'key_ingredients': 'Salicylic Acid 2%, Zinc PCA, Tea Tree Leaf Water, Willow Bark Extract',
        'full_ingredients': 'Aqua, Propanediol, Salicylic Acid, Zinc PCA, Melaleuca Alternifolia (Tea Tree) Leaf Water, Salix Alba (Willow) Bark Extract, Hydroxyethylcellulose, Sodium Hydroxide, Disodium EDTA, Phenoxyethanol',
        'usage_instructions': 'Apply 2-3 drops to clean skin at night. Focus on breakout-prone areas or T-zone. Follow with moisturizer.',
        'caution_info': 'Do not use together with Retinol in the same routine. Wear sunscreen daily during use.',
        'availability': 'in_stock',
        'is_bestseller': True,
        'is_new_arrival': False,
    },
    {
        'name': 'Multi-Peptide Youth Restorative Cream',
        'brand': 'Aura Luxe Skincare',
        'category': 'skincare',
        'description': 'Prestige firming night moisturizer packed with 5 biomimetic peptides, ceramides, and vegan squalane for plump, sculpted, youthful skin.',
        'price': Decimal('1499.00'),
        'discount_percent': 12,
        'rating': Decimal('4.88'),
        'review_count': 89,
        'image_url': 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'dry',
        'concern_tags': 'anti-aging,fine-lines,loss-of-firmness,hydration',
        'key_ingredients': 'Matrixyl 3000, Copper Peptides, Ceramide NP, Vegan Squalane, Shea Butter',
        'full_ingredients': 'Aqua, Caprylic/Capric Triglyceride, Squalane, Glycerin, Palmitoyl Tripeptide-1, Palmitoyl Tetrapeptide-7, Copper Tripeptide-1, Ceramide NP, Butyrospermum Parkii (Shea) Butter, Cetearyl Olivate, Sorbitan Olivate, Sodium Hyaluronate, Tocopherol, Phenoxyethanol, Carbomer',
        'usage_instructions': 'Warm a pearl-sized amount between fingertips and gently press into face, neck, and decolletage every evening.',
        'caution_info': 'Perform a patch test before first use. Store in a cool, dry place away from sunlight.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': True,
    },
    {
        'name': 'Invisible Broad-Spectrum SPF 50 PA++++ Gel',
        'brand': 'Joyory SunLab',
        'category': 'skincare',
        'description': 'Ultra-lightweight hybrid sunscreen that leaves zero white cast, absorbs in seconds, and provides broad-spectrum blue light and UV protection.',
        'price': Decimal('499.00'),
        'discount_percent': 0,
        'rating': Decimal('4.81'),
        'review_count': 310,
        'image_url': 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'sun-protection,dark-spots,anti-aging,pigmentation',
        'key_ingredients': 'Niacinamide, Hyaluronic Acid, Centella Asiatica, Tinosorb M, Uvinul A Plus',
        'full_ingredients': 'Aqua, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Ethylhexyl Triazone, Methylene Bis-Benzotriazolyl Tetramethylbutylphenol, Niacinamide, Centella Asiatica Extract, Sodium Hyaluronate, Silica, Carbomer, Tromethamine, Ethylhexylglycerin',
        'usage_instructions': 'Apply two finger lengths generously to face and neck 15 minutes prior to sun exposure. Reapply every 2 hours when outdoors.',
        'caution_info': 'Keep out of direct contact with eyes. For daytime use only.',
        'availability': 'in_stock',
        'is_bestseller': True,
        'is_new_arrival': False,
    },
    {
        'name': 'Rose Damascena Balancing Floral Toner',
        'brand': 'Lumina Botanicals',
        'category': 'skincare',
        'description': 'Steam-distilled pure organic rosewater toner infused with witch hazel and hyaluronic acid for balanced pH and instant hydration boost.',
        'price': Decimal('349.00'),
        'discount_percent': 20,
        'rating': Decimal('4.58'),
        'review_count': 94,
        'image_url': 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'combination',
        'concern_tags': 'hydration,redness,dullness,pores',
        'key_ingredients': 'Rosa Damascena Flower Water, Witch Hazel Extract, Hyaluronic Acid, Rosehip Seed Oil',
        'full_ingredients': 'Rosa Damascena Flower Water, Hamamelis Virginiana Water, Glycerin, Sodium Hyaluronate, Rosa Canina Seed Oil, Phenoxyethanol, Polysorbate 20, Potassium Sorbate',
        'usage_instructions': 'Spritz onto face after cleansing or sweep across skin using a reusable cotton round.',
        'caution_info': 'Discontinue use if signs of irritation or redness appear.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': False,
    },
    {
        'name': '0.3% Encapsulated Retinol Night Elixir',
        'brand': 'Aura Luxe Skincare',
        'category': 'skincare',
        'description': 'Advanced slow-release retinol serum microencapsulated with bakuchiol and squalane for maximum wrinkle-smoothing with minimum irritation.',
        'price': Decimal('1199.00'),
        'discount_percent': 10,
        'rating': Decimal('4.78'),
        'review_count': 118,
        'image_url': 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'normal',
        'concern_tags': 'anti-aging,fine-lines,hyperpigmentation,texture',
        'key_ingredients': 'Encapsulated Retinol 0.3%, Bakuchiol 1%, Squalane, Vitamin E',
        'full_ingredients': 'Caprylic/Capric Triglyceride, Squalane, Bakuchiol, Phospholipids, Retinol, Tocopheryl Acetate, Glycine Soja Oil, Helianthus Annuus Seed Oil, Phenoxyethanol',
        'usage_instructions': 'Use 2-3 nights per week initially, gradually increasing frequency. Apply 3 drops onto clean dry skin before night cream.',
        'caution_info': 'Do not combine with Vitamin C or direct acids in the same routine. Not recommended for pregnant or nursing mothers.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': True,
    },

    # =========================================================================
    # 2. HAIRCARE (Budget to Luxury, Scalp Care & Treatments)
    # =========================================================================
    {
        'name': 'Rosemary & Biotin Scalp Revitalizing Oil',
        'brand': 'Joyory Botanics',
        'category': 'haircare',
        'description': 'Potent hair and scalp treatment formulated with organic rosemary oil, biotin, castor oil, and peppermint to stimulate follicles and boost hair density.',
        'price': Decimal('399.00'),
        'discount_percent': 15,
        'rating': Decimal('4.74'),
        'review_count': 380,
        'image_url': 'https://images.unsplash.com/photo-1608248597359-00f745771ffb?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'hair-fall,thinning,scalp-health,dandruff',
        'key_ingredients': 'Rosemary Leaf Oil, Biotin, Pure Castor Oil, Peppermint Essential Oil, Jojoba Oil',
        'full_ingredients': 'Ricinus Communis (Castor) Seed Oil, Rosmarinus Officinalis (Rosemary) Leaf Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Biotin, Mentha Piperita (Peppermint) Oil, Tocopherol',
        'usage_instructions': 'Apply dropper directly to scalp partitions. Massage for 5 minutes with fingertips. Leave on for 2 hours or overnight before washing.',
        'caution_info': 'For external scalp application only. Rinse thoroughly if oil enters eyes.',
        'availability': 'in_stock',
        'is_bestseller': True,
        'is_new_arrival': False,
    },
    {
        'name': 'Deep Hydration Argan & Keratin Hair Mask',
        'brand': 'Lumina Salon Collection',
        'category': 'haircare',
        'description': 'Intensive reconstructive treatment mask enriched with Moroccan Argan oil and hydrolyzed keratin to revive dry, bleached, and heat-damaged hair.',
        'price': Decimal('799.00'),
        'discount_percent': 10,
        'rating': Decimal('4.82'),
        'review_count': 165,
        'image_url': 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'dry',
        'concern_tags': 'damage,frizz,split-ends,dryness',
        'key_ingredients': 'Moroccan Argan Oil, Hydrolyzed Keratin, Shea Butter, Provitamin B5',
        'full_ingredients': 'Aqua, Cetearyl Alcohol, Argania Spinosa (Argan) Kernel Oil, Butyrospermum Parkii Butter, Behentrimonium Chloride, Hydrolyzed Keratin, Panthenol, Dimethicone, Parfum, Citric Acid, Phenoxyethanol',
        'usage_instructions': 'After shampooing, apply generously from mid-lengths to ends. Leave on for 5-10 minutes, then rinse thoroughly with cool water.',
        'caution_info': 'Avoid contact with eyes. Keep out of reach of children.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': False,
    },
    {
        'name': 'Purifying Tea Tree Anti-Dandruff Clarifying Shampoo',
        'brand': 'Joyory Botanics',
        'category': 'haircare',
        'description': 'Gentle sulfate-free anti-dandruff cleanser with Australian Tea Tree and Salicylic Acid to eliminate flakes, calm itchiness, and rebalance oily scalp.',
        'price': Decimal('349.00'),
        'discount_percent': 0,
        'rating': Decimal('4.53'),
        'review_count': 120,
        'image_url': 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'oily',
        'concern_tags': 'dandruff,scalp-itchiness,oiliness,flakes',
        'key_ingredients': 'Tea Tree Oil, Salicylic Acid, Neem Extract, Aloe Vera Juice',
        'full_ingredients': 'Aqua, Sodium Lauroyl Sarcosinate, Cocamidopropyl Betaine, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Salicylic Acid, Azadirachta Indica (Neem) Leaf Extract, Aloe Barbadensis Leaf Juice, Polyquaternium-10, Phenoxyethanol',
        'usage_instructions': 'Massage into wet scalp for 2 minutes to allow actives to penetrate. Rinse thoroughly and follow with lightweight conditioner.',
        'caution_info': 'In case of eye contact, rinse immediately with clean water.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': True,
    },
    {
        'name': 'Luxury Caviar & Silk Protein Leave-In Conditioner',
        'brand': 'Aura Luxe Hair',
        'category': 'haircare',
        'description': 'High-performance heat-protective leave-in elixir with French caviar extract, silk amino acids, and UV filters for salon-mirror shine.',
        'price': Decimal('1650.00'),
        'discount_percent': 15,
        'rating': Decimal('4.91'),
        'review_count': 56,
        'image_url': 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'heat-protection,frizz,shine,color-safe',
        'key_ingredients': 'Caviar Extract, Hydrolyzed Silk, Camellia Seed Oil, Vitamin E',
        'full_ingredients': 'Aqua, Cyclopentasiloxane, Caviar Extract, Hydrolyzed Silk, Camellia Japonica Seed Oil, Dimethiconol, Fragrance (Parfum), Ethylhexyl Methoxycinnamate, Phenoxyethanol',
        'usage_instructions': 'Spray 3-5 pumps evenly through damp or dry hair before blow-drying or heat styling. Do not rinse.',
        'caution_info': 'Flammable until dry. Do not use near open flames.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': True,
    },

    # =========================================================================
    # 3. MAKEUP (Budget to Luxury, Everyday to Glam)
    # =========================================================================
    {
        'name': 'Featherlight Tinted Dewy Serum Foundation',
        'brand': 'Joyory Glow',
        'category': 'makeup',
        'description': 'Breathable skin tint infused with 1% Hyaluronic Acid and Squalane for light-to-medium radiant coverage that looks like natural fresh skin.',
        'price': Decimal('599.00'),
        'discount_percent': 10,
        'rating': Decimal('4.68'),
        'review_count': 188,
        'image_url': 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'dullness,uneven-tone,dryness,radiance',
        'key_ingredients': 'Hyaluronic Acid, Squalane, Vitamin C Derivative, Vitamin E',
        'full_ingredients': 'Aqua, Cyclopentasiloxane, Titanium Dioxide, Squalane, Glycerin, Sodium Hyaluronate, Ascorbyl Glucoside, Tocopherol, Iron Oxides (CI 77491, CI 77492, CI 77499), Phenoxyethanol',
        'usage_instructions': 'Shake well. Dispense 1-2 pumps and blend evenly across face using fingers, makeup sponge, or dense foundation brush.',
        'caution_info': 'Store upright at room temperature.',
        'availability': 'in_stock',
        'is_bestseller': True,
        'is_new_arrival': False,
    },
    {
        'name': 'Lash Sculpt Extreme Lengthening Mascara — Jet Black',
        'brand': 'Velvet Muse',
        'category': 'makeup',
        'description': 'Clump-free, smudge-proof defining mascara with flexible micro-bristles that coat every single lash for dramatic 24-hour curl and length.',
        'price': Decimal('449.00'),
        'discount_percent': 15,
        'rating': Decimal('4.76'),
        'review_count': 275,
        'image_url': 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'lashes,definition,long-wearing,smudge-proof',
        'key_ingredients': 'Carnauba Wax, Provitamin B5, Castor Oil, Mineral Pigments',
        'full_ingredients': 'Aqua, Cera Carnauba, Stearic Acid, Glyceryl Stearate, Ricinus Communis Seed Oil, Panthenol, CI 77499 (Iron Oxides), Phenoxyethanol',
        'usage_instructions': 'Wiggle the wand from lash base to tips. Layer a second coat while wet for maximum volume.',
        'caution_info': 'Ophthalmologist tested. Safe for contact lens wearers.',
        'availability': 'in_stock',
        'is_bestseller': True,
        'is_new_arrival': False,
    },
    {
        'name': 'Silk Touch Cream Blush — Petal Bloom',
        'brand': 'Joyory Glow',
        'category': 'makeup',
        'description': 'Melt-in weightless cream-to-powder blush infused with jojoba oil and rosehip extract that delivers a natural, youthful flushed glow.',
        'price': Decimal('349.00'),
        'discount_percent': 0,
        'rating': Decimal('4.62'),
        'review_count': 140,
        'image_url': 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'radiance,cheeks,glow,natural-finish',
        'key_ingredients': 'Jojoba Oil, Rosehip Seed Oil, Vitamin E, Mica',
        'full_ingredients': 'Caprylic/Capric Triglyceride, Simmondsia Chinensis Seed Oil, Mica, Cera Alba, Rosa Canina Fruit Oil, Tocopheryl Acetate, CI 77891, CI 77491, CI 15850',
        'usage_instructions': 'Dab lightly onto the apples of the cheeks with fingertips and blend upwards towards temples.',
        'caution_info': 'For external cosmetic use only.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': True,
    },
    {
        'name': 'Velvet Touch Matte Lipstick — Cinnamon Spice',
        'brand': 'Velvet Muse',
        'category': 'makeup',
        'description': 'Non-drying velvet matte lipstick enriched with murumuru butter and vitamin E for rich, highly pigmented 10-hour transfer-resistant color.',
        'price': Decimal('499.00'),
        'discount_percent': 20,
        'rating': Decimal('4.70'),
        'review_count': 190,
        'image_url': 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'lips,matte,pigmentation,long-lasting',
        'key_ingredients': 'Murumuru Butter, Vitamin E, Jojoba Esters, Mineral Pigments',
        'full_ingredients': 'Dimethicone, Astrocaryum Murumuru Seed Butter, Jojoba Esters, Silica, Tocopheryl Acetate, CI 77491, CI 77492, CI 77891, CI 15850, Aroma',
        'usage_instructions': 'Apply directly to lips starting from center cupid bow outward. For extra definition, line lips first.',
        'caution_info': 'Store away from direct heat to prevent softening.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': False,
    },
    {
        'name': '12-Pan Gilded Rose Luxury Eyeshadow Palette',
        'brand': 'Aura Luxe Cosmetics',
        'category': 'makeup',
        'description': 'A lavish edit of 12 ultra-buttery matte, metallic foil, and sparkling duo-chrome eyeshadows in romantic rose-golds, warm terracottas, and rich berries.',
        'price': Decimal('1899.00'),
        'discount_percent': 10,
        'rating': Decimal('4.94'),
        'review_count': 98,
        'image_url': 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'eyes,pigment,versatile,luxury',
        'key_ingredients': 'Spherical Silica, Jojoba Esters, Micronized Mica, Vitamin E',
        'full_ingredients': 'Talc, Mica, Silica, Magnesium Stearate, Simmondsia Chinensis Seed Oil, Tocopherol, Dimethicone, May Contain: CI 77891, CI 77491, CI 77499, CI 75470',
        'usage_instructions': 'Use eyeshadow brushes to blend transition shades in the crease and pat metallic foil shades onto lids using fingertips.',
        'caution_info': 'Cruelty-free, talc-purified, paraben-free.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': True,
    },

    # =========================================================================
    # 4. FRAGRANCE (Budget Mists to Luxury Extrait / EDP)
    # =========================================================================
    {
        'name': 'Golden Santal & Warm Amber Eau de Parfum',
        'brand': 'Joyory Privé',
        'category': 'fragrance',
        'description': 'A warm, intoxicating signature scent featuring Mysore sandalwood, creamy amber, bourbon vanilla, and spicy cardamom.',
        'price': Decimal('1499.00'),
        'discount_percent': 10,
        'rating': Decimal('4.87'),
        'review_count': 155,
        'image_url': 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'fragrance,warm,woody,long-lasting,sensual',
        'key_ingredients': 'Organic Sugar-Cane Alcohol, Mysore Sandalwood Essence, Amber Resin, Cardamom Oil',
        'full_ingredients': 'Alcohol Denat., Parfum (Fragrance), Aqua, Benzyl Benzoate, Coumarin, Eugenol, Limonene, Linalool',
        'usage_instructions': 'Spritz on pulse points — wrists, base of throat, behind earlobes, and inner elbows.',
        'caution_info': 'Flammable. Do not spray near eyes or open flame.',
        'availability': 'in_stock',
        'is_bestseller': True,
        'is_new_arrival': False,
    },
    {
        'name': 'Wild Jasmine & White Tea All-Over Body Mist',
        'brand': 'Lumina Botanicals',
        'category': 'fragrance',
        'description': 'An airy, uplifting everyday fragrance mist with sparkling bergamot, fresh white tea leaves, night-blooming jasmine, and sheer musk.',
        'price': Decimal('499.00'),
        'discount_percent': 15,
        'rating': Decimal('4.60'),
        'review_count': 112,
        'image_url': 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'refreshing,floral,daily-wear,lightweight',
        'key_ingredients': 'Jasmine Flower Extract, Camellia Sinensis (White Tea) Extract, Bergamot Peel Oil, Aloe Water',
        'full_ingredients': 'Aqua, Alcohol Denat., PEG-40 Hydrogenated Castor Oil, Fragrance, Jasminum Officinale Extract, Camellia Sinensis Leaf Extract, Aloe Barbadensis Leaf Juice, Ethylhexylglycerin',
        'usage_instructions': 'Mist generously over body and hair anytime you need a refreshing, floral aromatic lift.',
        'caution_info': 'Avoid spraying directly into eyes.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': True,
    },
    {
        'name': 'Royal Oud & Bulgarian Rose Extrait de Parfum',
        'brand': 'Aura Luxe Parfums',
        'category': 'fragrance',
        'description': 'Masterpiece luxury extrait with 30% fragrance concentration. Smoked agarwood, Damascus rose absolute, saffron, and velvety cashmeran.',
        'price': Decimal('2899.00'),
        'discount_percent': 5,
        'rating': Decimal('4.96'),
        'review_count': 42,
        'image_url': 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'luxury,niche,oud,rose,opulent',
        'key_ingredients': 'Natural Agarwood (Oud) Oil, Rosa Damascena Absolute, Saffron Extract, Cashmeran',
        'full_ingredients': 'Alcohol Denat., Parfum (Fragrance), Aqua, Citronellol, Geraniol, Farnesol, Isoeugenol, Alpha-Isomethyl Ionone',
        'usage_instructions': 'One to two sprays provide intense 18-hour sillage. Apply to collarbones and inner wrists.',
        'caution_info': 'Keep out of direct sunlight and extreme temperatures.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': True,
    },

    # =========================================================================
    # 5. BODY CARE (Body Washes, Butters, Scrubs, Hand Creams)
    # =========================================================================
    {
        'name': 'Whipped Madagascar Vanilla & Shea Body Butter',
        'brand': 'Joyory Body',
        'category': 'bodycare',
        'description': 'Decadent, rich body butter that melts upon contact, locking in 48-hour intense hydration for dry and rough skin.',
        'price': Decimal('499.00'),
        'discount_percent': 10,
        'rating': Decimal('4.84'),
        'review_count': 210,
        'image_url': 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'dry',
        'concern_tags': 'dryness,rough-skin,barrier-repair,deep-moisture',
        'key_ingredients': 'Raw Shea Butter, Madagascar Vanilla Extract, Sweet Almond Oil, Vitamin E',
        'full_ingredients': 'Aqua, Butyrospermum Parkii Butter, Prunus Amygdalus Dulcis Oil, Cetearyl Alcohol, Glycerin, Vanilla Planifolia Fruit Extract, Tocopheryl Acetate, Ceteareth-20, Phenoxyethanol',
        'usage_instructions': 'Massage lavishly all over clean skin after shower or bath, focusing on elbows, knees, and heels.',
        'caution_info': 'For external body use only.',
        'availability': 'in_stock',
        'is_bestseller': True,
        'is_new_arrival': False,
    },
    {
        'name': 'Exfoliating Coffee & Brown Sugar Body Polish',
        'brand': 'Joyory Body',
        'category': 'bodycare',
        'description': 'Natural physical body scrub blending roasted Arabica coffee grounds and organic cane sugar to smooth strawberry legs and boost lymphatic circulation.',
        'price': Decimal('399.00'),
        'discount_percent': 15,
        'rating': Decimal('4.67'),
        'review_count': 145,
        'image_url': 'https://images.unsplash.com/photo-1567928805192-d35d641494b8?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'texture,strawberry-legs,ingrown-hairs,smoothing',
        'key_ingredients': 'Arabica Coffee Grounds, Brown Cane Sugar, Coconut Oil, Sea Salt',
        'full_ingredients': 'Coffea Arabica Seed Powder, Sucrose, Cocos Nucifera (Coconut) Oil, Sodium Chloride, Prunus Amygdalus Dulcis Oil, Tocopherol, Citrus Sinensis Peel Oil',
        'usage_instructions': 'In the shower, massage onto wet skin in circular motions. Rinse thoroughly with warm water. Use 2-3 times weekly.',
        'caution_info': 'May make shower surfaces slippery. Do not apply on freshly shaved skin.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': False,
    },
    {
        'name': 'Intensive Ceramide & Almond Restorative Hand Cream',
        'brand': 'Lumina Botanicals',
        'category': 'bodycare',
        'description': 'Fast-absorbing, non-greasy barrier hand balm that heals cracked cuticles and dry hands subjected to frequent washing.',
        'price': Decimal('199.00'),
        'discount_percent': 0,
        'rating': Decimal('4.71'),
        'review_count': 320,
        'image_url': 'https://images.unsplash.com/photo-1556228722-d0b5d15c719e?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'sensitive',
        'concern_tags': 'dry-hands,cracked-skin,cuticle-care,barrier',
        'key_ingredients': 'Ceramide NP, Sweet Almond Oil, Colloidal Oatmeal, Shea Butter',
        'full_ingredients': 'Aqua, Cetearyl Alcohol, Butyrospermum Parkii Butter, Prunus Amygdalus Dulcis Oil, Glycerin, Ceramide NP, Avena Sativa (Oat) Kernel Flour, Dimethicone, Phenoxyethanol',
        'usage_instructions': 'Apply a pea-sized amount to hands and massage thoroughly into palms, knuckles, and nail beds as often as needed.',
        'caution_info': 'Hypoallergenic and fragrance-free.',
        'availability': 'in_stock',
        'is_bestseller': True,
        'is_new_arrival': False,
    },

    # =========================================================================
    # 6. NAIL CARE (Base, Polish, Treatment, Cuticle Oil)
    # =========================================================================
    {
        'name': 'Botanical Cuticle & Nail Strengthening Elixir',
        'brand': 'Joyory Nails',
        'category': 'nailcare',
        'description': 'Nutrient-packed dropper oil with sweet almond, jojoba, tea tree, and vitamin E to prevent peeling, splitting, and brittle nails.',
        'price': Decimal('249.00'),
        'discount_percent': 10,
        'rating': Decimal('4.64'),
        'review_count': 160,
        'image_url': 'https://images.unsplash.com/photo-1608248597359-00f745771ffb?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'brittle-nails,split-cuticles,nail-growth,hydration',
        'key_ingredients': 'Jojoba Seed Oil, Sweet Almond Oil, Tea Tree Leaf Oil, Vitamin E, Keratin Amino Acids',
        'full_ingredients': 'Simmondsia Chinensis Seed Oil, Prunus Amygdalus Dulcis Oil, Melaleuca Alternifolia Leaf Oil, Tocopheryl Acetate, Keratin Amino Acids',
        'usage_instructions': 'Apply one drop to each nail bed and massage into cuticles daily before bedtime.',
        'caution_info': 'For topical nail and cuticle application only.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': True,
    },
    {
        'name': 'Diamond Hardener 7-in-1 Base & Top Shield',
        'brand': 'Joyory Nails',
        'category': 'nailcare',
        'description': 'High-gloss dual base and top coat with diamond powder and calcium that hardens weak nails and prevents chipping for up to 14 days.',
        'price': Decimal('299.00'),
        'discount_percent': 0,
        'rating': Decimal('4.73'),
        'review_count': 95,
        'image_url': 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'nail-hardening,long-lasting,chip-resistant,gloss',
        'key_ingredients': 'Diamond Powder, Calcium Pantothenate, Biotin, Hexanal',
        'full_ingredients': 'Ethyl Acetate, Butyl Acetate, Nitrocellulose, Isopropyl Alcohol, Diamond Powder, Calcium Pantothenate, Biotin, Hexanal, CI 60725',
        'usage_instructions': 'Apply 1 coat under polish as a strengthening base, or 1 coat over dry nail polish as a high-shine protective seal.',
        'caution_info': 'Flammable. Keep away from heat and open flame.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': False,
    },
    {
        'name': 'Pastel Lilac Quick-Dry Gel Finish Nail Lacquer',
        'brand': 'Joyory Nails',
        'category': 'nailcare',
        'description': '10-toxin-free salon-grade nail lacquer that delivers opaque creamy pastel lilac color with an ultra-fast 60-second dry time.',
        'price': Decimal('189.00'),
        'discount_percent': 0,
        'rating': Decimal('4.52'),
        'review_count': 78,
        'image_url': 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'fast-dry,non-toxic,pastel,glossy',
        'key_ingredients': '10-Free Vegan Formula, Bamboo Extract, Vitamin E',
        'full_ingredients': 'Butyl Acetate, Ethyl Acetate, Nitrocellulose, Acetyl Tributyl Citrate, Bambusa Vulgaris Extract, CI 77891, CI 77742, CI 77491',
        'usage_instructions': 'Apply 2 thin coats allowing 1 minute between coats. Finish with clear top coat for extended wear.',
        'caution_info': 'Flammable. Store in a cool, dark place.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': True,
    },

    # =========================================================================
    # 7. TOOLS & ACCESSORIES (Budget to Premium)
    # =========================================================================
    {
        'name': 'Rose Quartz Dual-Ended Facial Roller & Sculpting Gua Sha',
        'brand': 'Joyory Beauty Tools',
        'category': 'tools',
        'description': 'Handcrafted 100% genuine Brazilian Rose Quartz facial roller and contoured Gua Sha stone designed to relieve facial tension and drain puffiness.',
        'price': Decimal('899.00'),
        'discount_percent': 20,
        'rating': Decimal('4.86'),
        'review_count': 240,
        'image_url': 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'puffiness,lymphatic-drainage,facial-sculpting,relaxation',
        'key_ingredients': '100% Natural Brazilian Rose Quartz, Zinc Alloy Gold-Tone Hardware',
        'full_ingredients': 'Natural Brazilian Rose Quartz Stone, Zinc Alloy Metal Frame with Silicone Noise-Free Insert',
        'usage_instructions': 'Apply facial oil or serum first. Glide the roller upward and outward across jawline, cheeks, and forehead for 5-10 minutes.',
        'caution_info': 'Fragile natural stone. Wash with mild soap and dry after each use. Store in padded pouch.',
        'availability': 'in_stock',
        'is_bestseller': True,
        'is_new_arrival': False,
    },
    {
        'name': 'Sonic Silicone Deep Pore Cleansing Device',
        'brand': 'Joyory Tech Beauty',
        'category': 'tools',
        'description': 'IPX7 waterproof sonic face brush with ultra-hygienic medical-grade silicone touchpoints and 6 speed pulsations to deep-clean pores and remove 99.5% of dirt.',
        'price': Decimal('1299.00'),
        'discount_percent': 15,
        'rating': Decimal('4.79'),
        'review_count': 175,
        'image_url': 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'oily',
        'concern_tags': 'deep-cleansing,blackheads,pores,exfoliation',
        'key_ingredients': 'Ultra-Hygienic Medical Silicone, Rechargeable Lithium-Ion Cell',
        'full_ingredients': 'Food-Grade Antibacterial Silicone, ABS Internal Core, USB Magnetic Charging Interface',
        'usage_instructions': 'Apply cleanser to damp face. Turn on device, select preferred vibration intensity, and glide gently over face for 1 minute.',
        'caution_info': 'Do not use with clay-based or gritty physical scrubs. USB magnetic charging included.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': True,
    },
    {
        'name': '100% Pure Mulberry Silk Sleep Mask & Pillowcase Set',
        'brand': 'Aura Luxe Living',
        'category': 'tools',
        'description': 'Luxury 22-Momme Grade 6A pure mulberry silk sleep set that minimizes pillow friction, prevents sleep creases, and keeps skin and hair hydrated.',
        'price': Decimal('2499.00'),
        'discount_percent': 10,
        'rating': Decimal('4.93'),
        'review_count': 64,
        'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'all',
        'concern_tags': 'sleep-creases,hair-friction,anti-aging,luxury',
        'key_ingredients': '100% Pure 22-Momme Grade 6A Mulberry Silk',
        'full_ingredients': '100% Pure Mulberry Silk (Outer and Inner Floss Filling)',
        'usage_instructions': 'Wear sleep mask comfortably over eyes each night. Hand wash silk pillowcase and mask in cold water with pH-neutral detergent.',
        'caution_info': 'Do not machine tumble dry or bleach. Iron on lowest silk setting if needed.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': True,
    },
    {
        'name': 'Natural Konjac Root Facial Cleansing Sponges (Duo Pack)',
        'brand': 'Joyory Pure',
        'category': 'tools',
        'description': '100% biodegradable, plant-based Konjac root sponges infused with green tea and bamboo charcoal for gentle daily micro-exfoliation.',
        'price': Decimal('249.00'),
        'discount_percent': 0,
        'rating': Decimal('4.57'),
        'review_count': 82,
        'image_url': 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
        'skin_type': 'sensitive',
        'concern_tags': 'gentle-exfoliation,sensitive-skin,eco-friendly,cleansing',
        'key_ingredients': '100% Konjac Root Fiber, Bamboo Charcoal, Organic Green Tea Powder',
        'full_ingredients': 'Amorphophallus Konjac Root Fiber, Activated Bamboo Charcoal Powder, Camellia Sinensis (Green Tea) Leaf Powder',
        'usage_instructions': 'Soak sponge in warm water for 2 minutes until completely soft. Massage face with or without cleanser in gentle circles. Hang to air dry.',
        'caution_info': '100% compostable. Replace every 6-8 weeks.',
        'availability': 'in_stock',
        'is_bestseller': False,
        'is_new_arrival': False,
    },
]

def seed_catalog():
    print(f"Starting product catalog expansion. Total new items to add/update: {len(EXPANDED_PRODUCTS)}")
    created_count = 0
    updated_count = 0

    for item in EXPANDED_PRODUCTS:
        name = item['name']
        prod, created = Product.objects.get_or_create(name=name, defaults=item)
        if created:
            created_count += 1
            print(f"  [+] Created: {name} (Category: {item['category']}, Price: Rs. {item['price']})")
        else:
            # Update fields to ensure freshest images and rich content
            for key, val in item.items():
                setattr(prod, key, val)
            prod.save()
            updated_count += 1
            print(f"  [*] Updated: {name}")

    total_count = Product.objects.count()
    print("\n" + "="*60)
    print(f"Product catalog expansion complete!")
    print(f"  - Newly Created: {created_count}")
    print(f"  - Updated: {updated_count}")
    print(f"  - Total Products in Database: {total_count}")
    print("="*60)

    # Category breakdown
    print("\nCategory Distribution:")
    for cat_code, cat_name in Product.CATEGORY_CHOICES:
        count = Product.objects.filter(category=cat_code).count()
        print(f"  - {cat_name} ({cat_code}): {count} products")

    # Price range breakdown
    under_500 = Product.objects.filter(price__lt=500).count()
    between_500_1000 = Product.objects.filter(price__gte=500, price__lte=1000).count()
    over_1000 = Product.objects.filter(price__gt=1000).count()
    print(f"\nPrice Distribution:")
    print(f"  - Budget (< Rs. 500): {under_500} products")
    print(f"  - Mid-Tier (Rs. 500 - Rs. 1000): {between_500_1000} products")
    print(f"  - Premium / Luxury (> Rs. 1000): {over_1000} products")

if __name__ == '__main__':
    seed_catalog()
