# Generated by Django 4.2.30 on 2026-09-20 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product display name', max_length=250)),
                ('brand', models.CharField(help_text='Brand or manufacturer name', max_length=120)),
                ('category', models.CharField(choices=[('skincare', 'Skincare'), ('haircare', 'Haircare'), ('makeup', 'Makeup'), ('fragrance', 'Fragrance'), ('bodycare', 'Body Care'), ('nailcare', 'Nail Care'), ('tools', 'Tools & Accessories')], db_index=True, help_text='Primary product category', max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Short marketing description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR (₹)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='Discount percentage (0-100)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0.00 – 5.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Number of customer reviews')),
                ('image_url', models.URLField(blank=True, default='', help_text='URL to product image (external or placeholder)')),
                ('skin_type', models.CharField(choices=[('all', 'All Skin Types'), ('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('normal', 'Normal')], default='all', help_text='Intended skin type', max_length=50)),
                ('concern_tags', models.CharField(blank=True, default='', help_text='Comma-separated concern tags, e.g. "acne,dark spots,hydration"', max_length=500)),
                ('key_ingredients', models.TextField(blank=True, default='', help_text='Key active ingredients (comma-separated or free text)')),
                ('full_ingredients', models.TextField(blank=True, default='', help_text='Complete INCI ingredient list')),
                ('usage_instructions', models.TextField(blank=True, default='', help_text='How to use this product')),
                ('caution_info', models.TextField(blank=True, default='', help_text='Warnings, allergens, or contraindications')),
                ('availability', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], db_index=True, default='in_stock', help_text='Current stock status', max_length=20)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
